show_downloads: true
google_analytics:
remote_theme: pmarsceill/just-the-docs
jekyll_admin:
  hidden_links:
    - posts
    - pages
    - staticfiles
    - datafiles
    - configuration
plugins:
  - jekyll-default-layout
